server:
  port: 8081
spring:  
  cloud:
    gateway:
      routes:
        - id: moviesRoute
          uri: lb://MOVIE
          predicates:
           - Path=/movies/**
        - id: catalagoRoute
          uri: lb://CATALAGO
          predicates:
           - Path=/catalago/**
